#ifndef USB_REPORT_IDS_H
#define USB_REPORT_IDS_H


#define REPORT_ID_INPUT                      1

#define REPORT_ID_OUTPUT_SET_EFFECT          1
#define REPORT_ID_OUTPUT_SET_ENVELOPE        2
#define REPORT_ID_OUTPUT_SET_CONDITION       3
#define REPORT_ID_OUTPUT_SET_PERIODIC        4
#define REPORT_ID_OUTPUT_SET_CONSTANT        5
#define REPORT_ID_OUTPUT_SET_RAMP            6
#define REPORT_ID_OUTPUT_EFFECT_OPERATION   10
#define REPORT_ID_OUTPUT_BLOCK_FREE         11
#define REPORT_ID_OUTPUT_DEVICE_CONTROL     12
#define REPORT_ID_OUTPUT_DEVICE_GAIN        13

#define REPORT_ID_FEATURE_CREATE_NEW_EFFECT  1
#define REPORT_ID_FEATURE_BLOCK_LOAD         2
#define REPORT_ID_FEATURE_POOL_REPORT        3

#endif // USB_REPORT_IDS_H